app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

front_index:
    path: /
    controller: App\Controller\FrontendController::mainAction
    methods: GET
    defaults:
        _format: html

